version: "3.3"
services:
  scraper:
    container_name: ratings_scraper
    build: ./scraper
    volumes:
      - ./scraper:/scraper
      - csv_path:/var/csv_path/
      - db_path:/var/db/
    command: python get_rating_history.py
    shm_size: 1gb

  web-app:
    container_name: ratings_web_app
    build: ./ratings_web_app
    volumes:
      - csv_path:/var/csv_path/
      - db_path:/var/db/
    ports:
      - 80:8080

  uploader:
    container_name: dataworld_uploader
    build: ./data.world_upload/
    volumes:
      - csv_path:/var/csv_path/


volumes:
     csv_path:
     db_path: